#!/bin/bash

#login into private registry
npm login

npm publish ./deploy/platform/editor/ --access=public

#logout when finished
npm logout
echo "Published successfully. Use 'npm install [package-name]' in the project you want to use it."
